<a href="https://colab.research.google.com/github/Tuevu110405/AIO_homework-M2-w1/blob/colab/basic_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 43.2MB/s]


In [ ]:
import numpy as np

In [ ]:
import matplotlib.image as mpimg
img = mpimg.imread('/content/dog.jpeg')
gray_img_01 = (np.max(img, axis=2)+np.min(img, axis=2))/2
gray_img_02 = np.sum(img, axis=2)/3
gray_img_03 = img[:,:,0]*0.21 + img[:,:,1]*0.72 + img[:,:,2]*0.07
print(gray_img_01[0,0])
print(gray_img_02[0,0])

print(gray_img_03[0,0])

102.5
107.66666666666667
126.22999999999999


In [ ]:
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 11.2MB/s]


In [ ]:
import pandas as pd
df = pd.read_csv('/content/advertising.csv')
data = df.to_numpy()

In [ ]:
print(data)

[[230.1  37.8  69.2  22.1]
 [ 44.5  39.3  45.1  10.4]
 [ 17.2  45.9  69.3  12. ]
 [151.5  41.3  58.5  16.5]
 [180.8  10.8  58.4  17.9]
 [  8.7  48.9  75.    7.2]
 [ 57.5  32.8  23.5  11.8]
 [120.2  19.6  11.6  13.2]
 [  8.6   2.1   1.    4.8]
 [199.8   2.6  21.2  15.6]
 [ 66.1   5.8  24.2  12.6]
 [214.7  24.    4.   17.4]
 [ 23.8  35.1  65.9   9.2]
 [ 97.5   7.6   7.2  13.7]
 [204.1  32.9  46.   19. ]
 [195.4  47.7  52.9  22.4]
 [ 67.8  36.6 114.   12.5]
 [281.4  39.6  55.8  24.4]
 [ 69.2  20.5  18.3  11.3]
 [147.3  23.9  19.1  14.6]
 [218.4  27.7  53.4  18. ]
 [237.4   5.1  23.5  17.5]
 [ 13.2  15.9  49.6   5.6]
 [228.3  16.9  26.2  20.5]
 [ 62.3  12.6  18.3   9.7]
 [262.9   3.5  19.5  17. ]
 [142.9  29.3  12.6  15. ]
 [240.1  16.7  22.9  20.9]
 [248.8  27.1  22.9  18.9]
 [ 70.6  16.   40.8  10.5]
 [292.9  28.3  43.2  21.4]
 [112.9  17.4  38.6  11.9]
 [ 97.2   1.5  30.   13.2]
 [265.6  20.    0.3  17.4]
 [ 95.7   1.4   7.4  11.9]
 [290.7   4.1   8.5  17.8]
 [266.9  43.8   5.   25.4]
 

In [ ]:
m_value = max(df['Sales'])
print(m_value)
print(np.where(df['Sales'] == m_value))

27.0
(array([175]),)


In [ ]:
print(df.iloc[np.where(df['Sales'] == m_value)])

        TV  Radio  Newspaper  Sales
175  276.9   48.9       41.8   27.0


In [ ]:
mean_value = np.mean(df['TV'])
print(mean_value)

147.0425


In [ ]:
count = np.array(df['Sales']) >= 20
print(count.sum())

40


In [ ]:

radio_values = df['Radio'][df['Sales'] >= 15]
mean_radio_value = np.mean(radio_values)
print(mean_radio_value)


26.22293577981651


In [ ]:
sum_sales = df['Sales'][df['Newspaper']> df['Newspaper'].mean()].sum()
print(sum_sales)

1405.1


In [ ]:


# Assuming df is already defined and has a 'Sales' column
mean = np.mean(df['Sales'])

evaluate = []
for i in range(len(df['Sales'])):
    if df['Sales'][i] > mean:
        evaluate.append('Good')
    elif df['Sales'][i] < mean:
        evaluate.append('Bad')
    else:
        evaluate.append('Average')

print(evaluate[7:10])


['Bad', 'Bad', 'Good']


In [ ]:
diff = np.abs(df['Sales']-mean)
closest_index = np.argmin(diff)
print(closest_index)
c_value = df['Sales'][closest_index]
print(c_value)
evaluate1 = []
for i in range(len(df['Sales'])):
    if df['Sales'][i] > c_value:
        evaluate1.append('Good')
    elif df['Sales'][i] < c_value:
        evaluate1.append('Bad')
    else:
        evaluate1.append('Average')

print(evaluate1[7:10])

123
15.2
['Bad', 'Bad', 'Good']
