<a href="https://colab.research.google.com/github/Tuevu110405/AIO_homework-M2/blob/colab/Vector_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def compute_vector_length(vector):
    len_of_vector =  np.sqrt(np.sum(vector**2))
    return len_of_vector



In [ ]:
def compute_dot_product(vector1, vector2):
    dot_product = np.sum(np.dot(vector1, vector2))
    return dot_product

In [ ]:
def matrix_multi_vector(matrix, vector):
    if  len(matrix[0]) != len(vector):
      print("This multiplication is not possible")
    else:
      result = matrix @ vector
      return result

In [ ]:
def matrix_multi_matrix(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
      print("This multiplication is not possible")
    else:
      result = matrix1 @ matrix2
      return result

# 1.5 Matrix inverse
det(A) = ad - bc = (-2)*(-4) - (6*8) = -40  
det(A) != 0  
=> det(A) = 1/-40*[[-4,-6],[-8,-2]]  
det(A) = [[0.1,0.15],[0.2,0.05]]


A- lambda * I  =


In [ ]:
def inverse_matrix(matrix):
    if np.linalg.det(matrix) == 0:
        print("Matrix is not invertible")
    else:
        inverse_matrix = np.linalg.inv(matrix)
        return inverse_matrix


# 2.1 Eigenvector and eigenvalue  
A- lambda * I = [[0.9-lambda, 0.2], [0.1, 0.8 - lambda]]
det(A-lambda*I) =0
=> lambda = 1 or lambda = 0.7  
(A-lambda*I) * v = 0  
lambda = 1 => v = (t;2t)=> normalize vector:v=(sqrt(5)/5;2*sqrt(5)/5)  
lambda = 0.7 => v = (t;-t)=> nỏmalize vector: v =(sqrt(2)/2;-sqrt(2)/2)


In [ ]:
def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

In [ ]:
A = np.array([[0.9,0.2],[0.1,0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(A)
print(eigenvalues)
print(eigenvectors)

[1.  0.7]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
def compute_cosine(v1, v2):
    cos = np.dot(v1, v2) / (compute_vector_length(v1) * compute_vector_length(v2))
    return cos

In [ ]:
from google.colab.patches import cv2_imshow
import cv2

def compute_difference(bg_img, input_img):
    bg_img = cv2.cvtColor(bg_img, cv2.COLOR_BGR2GRAY)
    input_img = cv2.cvtColor(input_img, cv2.COLOR_BGR2GRAY)
    difference = cv2.absdiff(bg_img, input_img)
    return difference


In [ ]:
def compute_binary_mask(difference):
    _, binary_mask = cv2.threshold(difference, 20, 255, cv2.THRESH_BINARY)
    return binary_mask

In [ ]:
def replace_background(bg1_image, bg2_image, ob_image):
    difference_single_channel = compute_difference(bg1_image, ob_image)
    binary_mask = compute_binary_mask(difference_single_channel)
    output = np.where(binary_mask == 255, bg2_image, ob_image)
    return output

# Bài tập trắc nghiệm

In [ ]:
vector = np. array ([ -2 , 4 , 9 , 21])
result = compute_vector_length (vector)
print ( round (result ,2) )

23.28


In [ ]:
v1 = np. array ([0 , 1 , -1 , 2])
v2 = np. array ([2 , 5 , 1 , 0])
result = compute_dot_product (v1 , v2)
print ( round (result ,2) )

4


In [ ]:
x = np. array ([[1 , 2] ,
[3 , 4]])
k = np. array ([1 , 2])
print ('result \n', x.dot (k) )

result 
 [ 5 11]


In [ ]:
x = np. array ([[ -1 , 2] ,
[3 , -4]])
k = np. array ([1 , 2])
print ('result \n', x@k )

result 
 [ 3 -5]


In [ ]:
m = np. array ([[ -1 , 1 , 1] , [0 , -4 , 9]])
v = np. array ([0 , 2 , 1])
result = matrix_multi_vector (m, v)
print ( result )

[3 1]


In [ ]:
m1 = np. array ([[0 , 1 , 2] , [2 , -3 , 1]])
m2 = np. array ([[1 , -3] ,[6 , 1] , [0 , -1]])
result = matrix_multi_matrix (m1 , m2)
print ( result )

[[  6  -1]
 [-16 -10]]


In [ ]:
m1 = np.eye(3)
m2 = np. array ([[1 , 1 , 1] ,[2 , 2 , 2] , [3 , 3 , 3]])
result = m1@m2
print ( result )


[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [ ]:
m1 = np.eye (2)
m1 = np. reshape (m1 ,( -1 ,4) ) [0]
m2 = np. array ([[1 , 1 , 1 , 1] ,[2 , 2 , 2 , 2] , [3 , 3 , 3 , 3] , [4 , 4 , 4 , 4]])
result = m1@m2
print ( result )

[5. 5. 5. 5.]


In [ ]:
m1 = np. array ([[1 , 2] , [3 , 4]])
m1 = np. reshape (m1 ,( -1 ,4) , "F") [0]
m2 = np. array ([[1 , 1 , 1 , 1] ,[2 , 2 , 2 , 2] , [3 , 3 , 3 , 3] , [4 , 4 , 4 , 4]])
result = m1@m2
print ( result )

[29 29 29 29]


In [ ]:
m1 = np. array ([[ -2 , 6] , [8 , -4]])
result = inverse_matrix (m1)
print ( result )

[[0.1  0.15]
 [0.2  0.05]]


In [ ]:
matrix = np. array ([[0.9 , 0.2] , [0.1 , 0.8]])
eigenvalues , eigenvectors = compute_eigenvalues_eigenvectors ( matrix )
print ( eigenvectors )

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
x = np. array ([1 , 2 , 3 , 4])
y = np. array ([1 , 0 , 3 , 0])
result = compute_cosine (x,y)
print ( round (result , 3) )

0.577
